# Generated by Django 5.0.1 on 2024-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.CharField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('total_price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, null=True)),
                ('roomno', models.CharField(blank=True, null=True)),
                ('descriptionn', models.CharField(blank=True, null=True)),
                ('price_per_night', models.BigIntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roomtype',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roomtype',
                'managed': False,
            },
        ),
    ]
