# Generated by Django 5.0.1 on 2024-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_usercustomuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_db',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
