# Generated by Django 5.0.1 on 2024-02-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hotel_db_delete_hotel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel_db',
            table='hotel_db',
        ),
    ]
