# Generated by Django 5.0.1 on 2024-02-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_hotel_db_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking_db',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room_db',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='roomtype_db',
        ),
    ]
