# Generated by Django 5.0.1 on 2024-02-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_table_alter_room_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomuser',
        ),
    ]
