# Generated by Django 5.0.1 on 2024-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_username_alter_customuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'User_customuser',
                'managed': False,
            },
        ),
    ]
