# Generated by Django 5.0.1 on 2024-02-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_usercustomuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustomuser',
        ),
    ]
