# Generated by Django 5.0.1 on 2024-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_delete_usercustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff_member',
            field=models.BooleanField(default=False),
        ),
    ]
